version: '3'

services:
  # Auth service
  auth_db:
    container_name: auth_db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=1 --log_bin=mysql-bin --binlog_format=ROW --binlog_do_db=auth --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: auth
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3307:3306'
    volumes:
      - './data/auth:/var/lib/mysql'
    networks:
      - stock

  # Stock service
  stock_db:
    container_name: stock_db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=2 --replicate-do-table=stock.users --bind-address=0.0.0.0 --replicate-rewrite-db=auth->stock
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: stock
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3308:3306'
    volumes:
      - './data/stock:/var/lib/mysql'
    networks:
      - stock

  # Blog service
  blog_db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --server-id=3 --replicate-do-table=blog.users --bind-address=0.0.0.0 --replicate-rewrite-db=auth->blog
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: blog
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3309:3306'
    volumes:
      - './data/blog:/var/lib/mysql'

  # Notify service
  notify_db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: notify
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3310:3306'
    volumes:
      - './data/notify:/var/lib/mysql'

networks:
  stock: